"""Generate the labelled SYNTHETIC SANDBOX dataset.

Writes, under data/processed/:
    states.pkl                   daily truth states of the toy atmosphere
    truth/truth_<year>.nc        daily verifying analysis ("observations")
    forecasts/fc_<YYYYMMDD>.nc   one ensemble forecast cycle, leads D1..D10
    static.nc                    terrain and land mask
    sandbox_events.csv           catalogue of synthetic systems (event labels)
    sandbox_indices.csv          daily large-scale indices
    MANIFEST.json                provenance, including the sandbox warning

The three stages (`states`, `truth`, `forecasts`) are independent and
resumable. Every random draw is seeded from the date or cycle it belongs to,
so re-running a stage reproduces identical output and partial runs can be
continued without invalidating what came before.

Every file carries a global attribute `data_mode = "SANDBOX_SYNTHETIC"` and a
`warning` attribute so that no downstream consumer can mistake it for real
observations.
"""
from __future__ import annotations

import json
import pickle
from datetime import date, timedelta
from pathlib import Path

import numpy as np
import pandas as pd
import xarray as xr

from ..config import Config, load_config
from ..grid import land_mask, make_grid, terrain_height
from .toy_model import ToyAtmosphere

SANDBOX_WARNING = (
    "SYNTHETIC SANDBOX DATA - generated by fbews.sandbox.toy_model. "
    "This is NOT real weather and must never be used operationally or "
    "presented as observations or as output of a real NWP model."
)

DET_VARS = [
    "precip", "t2m", "mslp", "u10", "v10", "tcwv", "cape",
    "z500", "u850", "v850", "t850", "rh700", "shear",
]
ENS_VARS = ["precip", "t2m", "mslp", "u10", "v10", "z500", "tcwv", "cape"]
TRUTH_VARS = ["precip", "t2m", "mslp", "u10", "v10", "z500", "tcwv", "cape", "u850", "v850"]

SPINUP_DAYS = 25


def _encoding(ds: xr.Dataset) -> dict:
    return {v: {"zlib": True, "complevel": 4, "dtype": "float32"} for v in ds.data_vars}


def _atmos(cfg: Config):
    lats, lons = make_grid(cfg.domain, cfg.resolution)
    land = land_mask(lats, lons)
    terrain = terrain_height(lats, lons)
    return lats, lons, land, terrain, ToyAtmosphere(lats, lons, terrain, land)


def _field_rng(seed: int, d: date) -> np.random.Generator:
    """Deterministic per-date generator so stages can be run independently."""
    return np.random.default_rng(seed * 1_000_003 + d.toordinal())


def _dates(cfg: Config, quick: bool) -> tuple[date, date, list[date]]:
    sb = cfg["sandbox"]
    start = date.fromisoformat(sb["start_date"])
    end = date.fromisoformat(sb["end_date"])
    if quick:
        end = min(end, start + timedelta(days=120))
    cycles, c = [], start
    while c <= end:
        cycles.append(c)
        c += timedelta(days=int(sb["cycle_interval_days"]))
    return start, end, cycles


# ---------------------------------------------------------------------------
# Stage 1: truth states, static fields, event and index catalogues
# ---------------------------------------------------------------------------
def generate_states(cfg: Config | None = None, quick: bool = False, verbose: bool = True) -> Path:
    cfg = cfg or load_config()
    sb = cfg["sandbox"]
    start, end, _ = _dates(cfg, quick)
    lats, lons, land, terrain, atmos = _atmos(cfg)
    proc = cfg.path("processed")

    rng = np.random.default_rng(int(sb["seed"]))
    state = atmos.spin_up(start - timedelta(days=SPINUP_DAYS), rng)

    states: dict[date, object] = {}
    events: list[dict] = []
    indices: list[dict] = []
    d = start - timedelta(days=SPINUP_DAYS)
    last = end + timedelta(days=max(cfg.lead_days) + 2)
    while d <= last:
        state = atmos.advance(state, d, rng)
        if d >= start:
            states[d] = state.copy()
            indices.append({
                "date": d.isoformat(),
                "mjo_phase": round(float(state.mjo_phase), 4),
                "mjo_amplitude": round(float(state.mjo_amp), 4),
                "heat_index": round(float(state.heat), 4),
                "jet_index": round(float(state.jet), 4),
                "n_systems": len(state.systems),
            })
            for s in state.systems:
                events.append({
                    "date": d.isoformat(), "kind": s.kind,
                    "lat": round(float(s.lat), 3), "lon": round(float(s.lon), 3),
                    "depth_hpa": round(float(s.depth), 3),
                    "radius_deg": round(float(s.radius), 3), "age_days": int(s.age),
                })
        d += timedelta(days=1)

    with open(proc / "states.pkl", "wb") as fh:
        pickle.dump(states, fh)
    pd.DataFrame(events).to_csv(proc / "sandbox_events.csv", index=False)
    pd.DataFrame(indices).to_csv(proc / "sandbox_indices.csv", index=False)

    static = xr.Dataset(
        {"terrain": (("lat", "lon"), terrain), "land": (("lat", "lon"), land.astype("int8"))},
        coords={"lat": lats, "lon": lons},
        attrs={
            "land_mask_source": "global_land_mask package (Natural Earth derived) - REAL",
            "terrain_source": "idealised smooth orography (sandbox only)",
            "data_mode": "SANDBOX_SYNTHETIC",
        },
    )
    static.to_netcdf(proc / "static.nc")
    if verbose:
        print(f"states: {len(states)} days, {len(events)} system records", flush=True)
    return proc / "states.pkl"


def load_states(cfg: Config) -> dict:
    with open(cfg.path("processed") / "states.pkl", "rb") as fh:
        return pickle.load(fh)


# ---------------------------------------------------------------------------
# Stage 2: truth ("observed") fields
# ---------------------------------------------------------------------------
def generate_truth(cfg: Config | None = None, quick: bool = False, years: list[int] | None = None,
                   verbose: bool = True) -> list[Path]:
    cfg = cfg or load_config()
    seed = int(cfg["sandbox"]["seed"])
    lats, lons, _, _, atmos = _atmos(cfg)
    states = load_states(cfg)
    proc = cfg.path("processed")
    (proc / "truth").mkdir(exist_ok=True)

    by_year: dict[int, list[date]] = {}
    for d in sorted(states):
        by_year.setdefault(d.year, []).append(d)

    written = []
    for year, days in by_year.items():
        if years and year not in years:
            continue
        out = proc / "truth" / f"truth_{year}.nc"
        if out.exists():
            written.append(out)
            continue
        buf = {v: [] for v in TRUTH_VARS}
        for d in days:
            f = atmos.fields(states[d], d, _field_rng(seed, d), model_bias=False)
            for v in TRUTH_VARS:
                buf[v].append(f[v])
        ds = xr.Dataset(
            {v: (("time", "lat", "lon"), np.stack(buf[v]).astype("float32")) for v in TRUTH_VARS},
            coords={"time": np.array([np.datetime64(d) for d in days]), "lat": lats, "lon": lons},
            attrs={"data_mode": "SANDBOX_SYNTHETIC", "warning": SANDBOX_WARNING,
                   "role": "verifying analysis (truth) for the sandbox",
                   "units": "precip mm/day, t2m K, mslp hPa, wind m/s, z500 m"},
        )
        ds.to_netcdf(out, encoding=_encoding(ds))
        written.append(out)
        if verbose:
            print(f"truth {year}: {len(days)} days", flush=True)
    return written


# ---------------------------------------------------------------------------
# Stage 3: ensemble forecast cycles
# ---------------------------------------------------------------------------
def generate_forecasts(cfg: Config | None = None, quick: bool = False, limit: int | None = None,
                       verbose: bool = True) -> list[Path]:
    cfg = cfg or load_config()
    sb = cfg["sandbox"]
    seed, members = int(sb["seed"]), int(sb["members"])
    lats, lons, _, _, atmos = _atmos(cfg)
    states = load_states(cfg)
    _, _, cycles = _dates(cfg, quick)
    leads = cfg.lead_days
    proc = cfg.path("processed")
    (proc / "forecasts").mkdir(exist_ok=True)

    written, done = [], 0
    for n, c0 in enumerate(cycles):
        out = proc / "forecasts" / f"fc_{c0:%Y%m%d}.nc"
        if out.exists():
            written.append(out)
            continue
        if limit is not None and done >= limit:
            break
        rng = np.random.default_rng(seed + 977 * n)
        base = states[c0]
        member_states = [base.copy() if m == 0 else atmos.perturb_initial(base, rng)
                         for m in range(members)]
        per_lead: dict[int, dict[str, np.ndarray]] = {}
        for lead in range(1, max(leads) + 1):
            valid = c0 + timedelta(days=lead)
            stacks: dict[str, list[np.ndarray]] = {v: [] for v in DET_VARS}
            for m in range(members):
                member_states[m] = atmos.advance(member_states[m], valid, rng, model_error=True)
                f = atmos.fields(member_states[m], valid, rng, model_bias=True)
                for v in DET_VARS:
                    stacks[v].append(f[v])
            if lead in leads:
                per_lead[lead] = {v: np.stack(stacks[v]) for v in DET_VARS}

        order = sorted(per_lead)
        data_vars: dict[str, tuple] = {}
        for v in DET_VARS:
            data_vars[f"det_{v}"] = (("lead", "lat", "lon"),
                                     np.stack([per_lead[l][v][0] for l in order]).astype("float32"))
        for v in ENS_VARS:
            arr = np.stack([per_lead[l][v] for l in order])          # (lead, member, lat, lon)
            data_vars[f"ensmean_{v}"] = (("lead", "lat", "lon"), arr.mean(1).astype("float32"))
            data_vars[f"ensstd_{v}"] = (("lead", "lat", "lon"), arr.std(1).astype("float32"))
        parr = np.stack([per_lead[l]["precip"] for l in order])
        for q in (25, 50, 75, 90):
            data_vars[f"precip_q{q}"] = (("lead", "lat", "lon"),
                                         np.percentile(parr, q, axis=1).astype("float32"))
        for thr in (10.0, 25.0, 50.0):
            data_vars[f"pop_gt{int(thr)}"] = (("lead", "lat", "lon"),
                                              (parr > thr).mean(1).astype("float32"))
        tarr = np.stack([per_lead[l]["t2m"] for l in order])
        data_vars["t2m_range"] = (("lead", "lat", "lon"), (tarr.max(1) - tarr.min(1)).astype("float32"))
        marr = np.stack([per_lead[l]["mslp"] for l in order])
        data_vars["mslp_min"] = (("lead", "lat", "lon"), marr.min(1).astype("float32"))

        ds = xr.Dataset(
            data_vars,
            coords={"lead": np.array(order, dtype="int16"), "lat": lats, "lon": lons},
            attrs={"data_mode": "SANDBOX_SYNTHETIC", "warning": SANDBOX_WARNING,
                   "forecast_cycle": c0.isoformat() + "T00:00:00Z",
                   "ensemble_members": members,
                   "accumulation_hours": cfg["forecast"]["accumulation_window_hours"],
                   "units_precip": "mm/day"},
        )
        ds.to_netcdf(out, encoding=_encoding(ds))
        written.append(out)
        done += 1
        if verbose and done % 20 == 0:
            print(f"cycle {n + 1}/{len(cycles)}  {c0}", flush=True)
    return written


def generate_prev_cycles(cfg: Config | None = None, quick: bool = False, limit: int | None = None,
                         verbose: bool = True) -> list[Path]:
    """Generate the T-24 h companion cycle for every main cycle.

    Forecast-volatility features compare two consecutive forecast cycles for
    the *same valid time*, so the cycle issued 24 h earlier must be available
    at lead+1. Only the fields needed for revision diagnostics are stored.
    """
    cfg = cfg or load_config()
    sb = cfg["sandbox"]
    seed, members = int(sb["seed"]), int(sb["members"])
    lats, lons, _, _, atmos = _atmos(cfg)
    states = load_states(cfg)
    _, _, cycles = _dates(cfg, quick)
    leads = cfg.lead_days
    prev_leads = [l + 1 for l in leads]
    proc = cfg.path("processed")
    (proc / "forecasts_prev").mkdir(exist_ok=True)

    keep = ["precip", "t2m", "mslp", "u10", "v10"]
    written, done = [], 0
    for n, c_main in enumerate(cycles):
        c0 = c_main - timedelta(days=1)
        out = proc / "forecasts_prev" / f"fcprev_{c_main:%Y%m%d}.nc"
        if out.exists():
            written.append(out)
            continue
        if c0 not in states:
            continue
        if limit is not None and done >= limit:
            break
        rng = np.random.default_rng(seed + 977 * n + 13)
        base = states[c0]
        member_states = [base.copy() if m == 0 else atmos.perturb_initial(base, rng)
                         for m in range(members)]
        per_lead: dict[int, dict[str, np.ndarray]] = {}
        for lead in range(1, max(prev_leads) + 1):
            valid = c0 + timedelta(days=lead)
            stacks: dict[str, list[np.ndarray]] = {v: [] for v in keep}
            for m in range(members):
                member_states[m] = atmos.advance(member_states[m], valid, rng, model_error=True)
                f = atmos.fields(member_states[m], valid, rng, model_bias=True)
                for v in keep:
                    stacks[v].append(f[v])
            if lead in prev_leads:
                per_lead[lead] = {v: np.stack(stacks[v]) for v in keep}

        order = sorted(per_lead)
        data_vars = {}
        for v in keep:
            arr = np.stack([per_lead[l][v] for l in order])
            data_vars[f"ensmean_{v}"] = (("lead", "lat", "lon"), arr.mean(1).astype("float32"))
        arr = np.stack([per_lead[l]["precip"] for l in order])
        data_vars["ensstd_precip"] = (("lead", "lat", "lon"), arr.std(1).astype("float32"))
        ds = xr.Dataset(
            data_vars,
            coords={"lead": np.array(order, dtype="int16"), "lat": lats, "lon": lons},
            attrs={"data_mode": "SANDBOX_SYNTHETIC", "warning": SANDBOX_WARNING,
                   "forecast_cycle": c0.isoformat() + "T00:00:00Z",
                   "role": "T-24h companion cycle for forecast-volatility features",
                   "paired_with_cycle": c_main.isoformat()},
        )
        ds.to_netcdf(out, encoding=_encoding(ds))
        written.append(out)
        done += 1
        if verbose and done % 40 == 0:
            print(f"prev cycle {n + 1}/{len(cycles)}", flush=True)
    return written


def generate_cycle_series(cfg: Config | None = None, dates: list[date] | None = None,
                         verbose: bool = True) -> list[Path]:
    """Generate main + T-24 companion cycles for arbitrary dates.

    Used to build dense daily cycle sequences around case-study events so the
    "could the system have warned us?" timeline has real consecutive cycles.
    """
    cfg = cfg or load_config()
    sb = cfg["sandbox"]
    seed, members = int(sb["seed"]), int(sb["members"])
    lats, lons, _, _, atmos = _atmos(cfg)
    states = load_states(cfg)
    leads = cfg.lead_days
    proc = cfg.path("processed")
    (proc / "forecasts").mkdir(exist_ok=True)
    (proc / "forecasts_prev").mkdir(exist_ok=True)
    written = []
    for c_main in dates or []:
        for tag, c0 in (("main", c_main), ("prev", c_main - timedelta(days=1))):
            if c0 not in states:
                continue
            out = (proc / "forecasts" / f"fc_{c0:%Y%m%d}.nc") if tag == "main" else \
                  (proc / "forecasts_prev" / f"fcprev_{c_main:%Y%m%d}.nc")
            if out.exists():
                written.append(out)
                continue
            n = c0.toordinal() % 100000
            rng = np.random.default_rng(seed + 977 * n + (0 if tag == "main" else 13))
            member_states = [states[c0].copy() if m == 0 else atmos.perturb_initial(states[c0], rng)
                             for m in range(members)]
            want = leads if tag == "main" else [l + 1 for l in leads]
            per_lead = {}
            for lead in range(1, max(want) + 1):
                valid = c0 + timedelta(days=lead)
                stacks = {v: [] for v in DET_VARS}
                for m in range(members):
                    member_states[m] = atmos.advance(member_states[m], valid, rng, model_error=True)
                    f = atmos.fields(member_states[m], valid, rng, model_bias=True)
                    for v in DET_VARS:
                        stacks[v].append(f[v])
                if lead in want:
                    per_lead[lead] = {v: np.stack(stacks[v]) for v in DET_VARS}
            order = sorted(per_lead)
            data_vars = {}
            if tag == "main":
                for v in DET_VARS:
                    data_vars[f"det_{v}"] = (("lead", "lat", "lon"),
                                             np.stack([per_lead[l][v][0] for l in order]).astype("float32"))
                for v in ENS_VARS:
                    arr = np.stack([per_lead[l][v] for l in order])
                    data_vars[f"ensmean_{v}"] = (("lead", "lat", "lon"), arr.mean(1).astype("float32"))
                    data_vars[f"ensstd_{v}"] = (("lead", "lat", "lon"), arr.std(1).astype("float32"))
                parr = np.stack([per_lead[l]["precip"] for l in order])
                for q in (25, 50, 75, 90):
                    data_vars[f"precip_q{q}"] = (("lead", "lat", "lon"),
                                                 np.percentile(parr, q, axis=1).astype("float32"))
                for thr in (10.0, 25.0, 50.0):
                    data_vars[f"pop_gt{int(thr)}"] = (("lead", "lat", "lon"),
                                                      (parr > thr).mean(1).astype("float32"))
                tarr = np.stack([per_lead[l]["t2m"] for l in order])
                data_vars["t2m_range"] = (("lead", "lat", "lon"), (tarr.max(1) - tarr.min(1)).astype("float32"))
                marr = np.stack([per_lead[l]["mslp"] for l in order])
                data_vars["mslp_min"] = (("lead", "lat", "lon"), marr.min(1).astype("float32"))
            else:
                for v in ["precip", "t2m", "mslp", "u10", "v10"]:
                    arr = np.stack([per_lead[l][v] for l in order])
                    data_vars[f"ensmean_{v}"] = (("lead", "lat", "lon"), arr.mean(1).astype("float32"))
                arr = np.stack([per_lead[l]["precip"] for l in order])
                data_vars["ensstd_precip"] = (("lead", "lat", "lon"), arr.std(1).astype("float32"))
            ds = xr.Dataset(data_vars,
                            coords={"lead": np.array(order, dtype="int16"), "lat": lats, "lon": lons},
                            attrs={"data_mode": "SANDBOX_SYNTHETIC", "warning": SANDBOX_WARNING,
                                   "forecast_cycle": c0.isoformat() + "T00:00:00Z",
                                   "role": "case-study cycle series"})
            ds.to_netcdf(out, encoding=_encoding(ds))
            written.append(out)
        if verbose:
            print(f"case-study cycle {c_main}", flush=True)
    return written


def write_manifest(cfg: Config | None = None, quick: bool = False) -> dict:
    cfg = cfg or load_config()
    sb = cfg["sandbox"]
    start, end, cycles = _dates(cfg, quick)
    lats, lons = make_grid(cfg.domain, cfg.resolution)
    proc = cfg.path("processed")
    n_files = len(list((proc / "forecasts").glob("fc_*.nc")))
    manifest = {
        "data_mode": "SANDBOX_SYNTHETIC",
        "warning": SANDBOX_WARNING,
        "generator": "fbews.sandbox.toy_model.ToyAtmosphere",
        "seed": int(sb["seed"]),
        "period": [start.isoformat(), end.isoformat()],
        "cycle_interval_days": int(sb["cycle_interval_days"]),
        "n_cycles_expected": len(cycles),
        "n_cycles_written": n_files,
        "members": int(sb["members"]),
        "lead_days": cfg.lead_days,
        "grid": {"resolution_deg": cfg.resolution,
                 "lat": [float(lats[0]), float(lats[-1])],
                 "lon": [float(lons[0]), float(lons[-1])],
                 "shape": [len(lats), len(lons)]},
        "real_components": [
            "land-sea mask (global_land_mask / Natural Earth)",
            "India state boundaries GeoJSON (datta07/INDIAN-SHAPEFILES, MIT)",
        ],
    }
    (proc / "MANIFEST.json").write_text(json.dumps(manifest, indent=2))
    return manifest


def generate(cfg: Config | None = None, quick: bool = False, verbose: bool = True) -> dict:
    cfg = cfg or load_config()
    generate_states(cfg, quick, verbose)
    generate_truth(cfg, quick, verbose=verbose)
    generate_forecasts(cfg, quick, verbose=verbose)
    return write_manifest(cfg, quick)


if __name__ == "__main__":  # pragma: no cover
    generate()
